# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Go mod tidy
        run: go mod tidy

      - name: Run go tests
        run: go test -v ./...

      - name: Build volback binary
        run: go build -o volback ./cmd/volback

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        working-directory: ./e2e
        run: pip install poetry

      - name: Install Python dependencies
        working-directory: ./e2e
        run: poetry install

      - name: Run E2E tests
        working-directory: ./e2e
        run: poetry run python3 -m pytest -vvrP
